const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');
const production = process.argv.includes('--production');
const watch = process.argv.includes('--watch');

// Generate renderer/generated/katexCss.ts: KaTeX's stylesheet with every
// `url(fonts/*.woff2)` rewritten to a base64 data URI, and the woff/ttf
// fallback `src` entries dropped. The notebook-renderer webview sandbox can't
// resolve relative font URLs, so inlining woff2 (universally supported in
// modern webviews) makes math fully self-contained — no network, no relative
// font fetch. Regenerated on every build; the file is gitignored.
//
// NOTE: this generated file (renderer/generated/katexCss.ts) must exist before
// tsc/tests run; a fresh clone produces it via `npm run build`.
function generateKatexCss() {
  const katexDist = path.dirname(require.resolve('katex/dist/katex.min.css'));
  let css = fs.readFileSync(path.join(katexDist, 'katex.min.css'), 'utf8');

  // Rewrite each @font-face `src:...` (which lists woff2, woff, ttf) to a single
  // woff2 data-URI source. Matches from `src:` up to the next `}` (end of rule).
  css = css.replace(/src:[^}]*?url\(fonts\/([^)]+?\.woff2)\)[^}]*?(?=[};])/g, (_m, file) => {
    let data;
    try {
      data = fs.readFileSync(path.join(katexDist, 'fonts', file)).toString('base64');
    } catch (err) {
      throw new Error(`katex font inlining failed for ${file}: ${String(err)}`);
    }
    return `src:url(data:font/woff2;base64,${data}) format("woff2")`;
  });

  // Quote-agnostic guard: catch ANY surviving fonts/ reference regardless of
  // quoting (e.g. url(fonts/…), url("fonts/…"), url('fonts/…')) so a future
  // KaTeX quoting change can't silently ship broken relative font URLs.
  if (/url\(\s*["']?fonts\//.test(css)) {
    throw new Error('katex CSS still references relative fonts/ URLs after inlining');
  }

  const outDir = path.join(__dirname, 'renderer', 'generated');
  fs.mkdirSync(outDir, { recursive: true });
  const banner = '// AUTO-GENERATED by esbuild.js — do not edit. KaTeX CSS with woff2 fonts inlined.\n';
  fs.writeFileSync(
    path.join(outDir, 'katexCss.ts'),
    banner + 'export const KATEX_CSS = ' + JSON.stringify(css) + ';\n'
  );
}

async function build() {
  generateKatexCss();
  // Extension host bundle (CommonJS, vscode external)
  const ext = await esbuild.context({
    entryPoints: ['src/extension.ts'],
    bundle: true,
    platform: 'node',
    format: 'cjs',
    external: ['vscode'],
    outfile: 'dist/extension.js',
    sourcemap: !production,
    minify: production,
  });
  // Renderer bundle (ESM, runs in the notebook webview)
  const rend = await esbuild.context({
    entryPoints: ['renderer/mystRenderer.ts'],
    bundle: true,
    platform: 'browser',
    format: 'esm',
    outfile: 'dist/renderer/mystRenderer.js',
    sourcemap: !production,
    minify: production,
  });
  // Graph webview bundle (browser context — Lit + force-graph)
  const graphWebview = await esbuild.context({
    entryPoints: ['src/graph/webview-src/main.ts'],
    bundle: true,
    platform: 'browser',
    format: 'iife',
    outfile: 'dist/graph/webview.js',
    sourcemap: !production,
    minify: production,
  });
  if (watch) { await ext.watch(); await rend.watch(); await graphWebview.watch(); }
  else { await ext.rebuild(); await rend.rebuild(); await graphWebview.rebuild(); await ext.dispose(); await rend.dispose(); await graphWebview.dispose(); }
}
build().catch((e) => { console.error(e); process.exit(1); });
