export interface MathSymbol {
  latex: string;
  description: string;
  unicode?: string;
  snippet?: string; // VS Code SnippetString with $1/$2 placeholders
}

// O(1) lookup map built from the array
export const MATH_SYMBOLS_BY_LATEX: Map<string, MathSymbol> = new Map();

export const MATH_SYMBOLS: MathSymbol[] = [
  // ===== Category 1: Greek lowercase (28 + \omicron) =====
  { latex: '\\alpha', description: 'alpha', unicode: 'α' },
  { latex: '\\beta', description: 'beta', unicode: 'β' },
  { latex: '\\gamma', description: 'gamma', unicode: 'γ' },
  { latex: '\\delta', description: 'delta', unicode: 'δ' },
  { latex: '\\epsilon', description: 'epsilon', unicode: 'ε' },
  { latex: '\\varepsilon', description: 'epsilon (var)', unicode: 'ε' },
  { latex: '\\zeta', description: 'zeta', unicode: 'ζ' },
  { latex: '\\eta', description: 'eta', unicode: 'η' },
  { latex: '\\theta', description: 'theta', unicode: 'θ' },
  { latex: '\\vartheta', description: 'theta (var)', unicode: 'ϑ' },
  { latex: '\\iota', description: 'iota', unicode: 'ι' },
  { latex: '\\kappa', description: 'kappa', unicode: 'κ' },
  { latex: '\\lambda', description: 'lambda', unicode: 'λ' },
  { latex: '\\mu', description: 'mu', unicode: 'μ' },
  { latex: '\\nu', description: 'nu', unicode: 'ν' },
  { latex: '\\xi', description: 'xi', unicode: 'ξ' },
  { latex: '\\omicron', description: 'omicron', unicode: 'ο' },
  { latex: '\\pi', description: 'pi', unicode: 'π' },
  { latex: '\\varpi', description: 'pi (var)', unicode: 'ϖ' },
  { latex: '\\rho', description: 'rho', unicode: 'ρ' },
  { latex: '\\sigma', description: 'sigma', unicode: 'σ' },
  { latex: '\\varsigma', description: 'sigma (var)', unicode: 'ς' },
  { latex: '\\tau', description: 'tau', unicode: 'τ' },
  { latex: '\\upsilon', description: 'upsilon', unicode: 'υ' },
  { latex: '\\phi', description: 'phi', unicode: 'φ' },
  { latex: '\\varphi', description: 'phi (var)', unicode: 'φ' },
  { latex: '\\chi', description: 'chi', unicode: 'χ' },
  { latex: '\\psi', description: 'psi', unicode: 'ψ' },
  { latex: '\\omega', description: 'omega', unicode: 'ω' },

  // ===== Category 2: Greek uppercase (11) =====
  { latex: '\\Gamma', description: 'Gamma', unicode: 'Γ' },
  { latex: '\\Delta', description: 'Delta', unicode: 'Δ' },
  { latex: '\\Theta', description: 'Theta', unicode: 'Θ' },
  { latex: '\\Lambda', description: 'Lambda', unicode: 'Λ' },
  { latex: '\\Xi', description: 'Xi', unicode: 'Ξ' },
  { latex: '\\Pi', description: 'Pi', unicode: 'Π' },
  { latex: '\\Sigma', description: 'Sigma', unicode: 'Σ' },
  { latex: '\\Upsilon', description: 'Upsilon', unicode: 'Υ' },
  { latex: '\\Phi', description: 'Phi', unicode: 'Φ' },
  { latex: '\\Psi', description: 'Psi', unicode: 'Ψ' },
  { latex: '\\Omega', description: 'Omega', unicode: 'Ω' },

  // ===== Category 3: Hebrew/misc letters (14) =====
  { latex: '\\aleph', description: 'aleph', unicode: 'ℵ' },
  { latex: '\\beth', description: 'beth', unicode: 'ℶ' },
  { latex: '\\gimel', description: 'gimel', unicode: 'ℷ' },
  { latex: '\\daleth', description: 'daleth', unicode: 'ℸ' },
  { latex: '\\hbar', description: 'h-bar', unicode: 'ℏ' },
  { latex: '\\hslash', description: 'hslash', unicode: 'ℏ' },
  { latex: '\\ell', description: 'ell', unicode: 'ℓ' },
  { latex: '\\wp', description: 'Weierstrass p', unicode: '℘' },
  { latex: '\\Im', description: 'imaginary part', unicode: 'ℑ' },
  { latex: '\\Re', description: 'real part', unicode: 'ℜ' },
  { latex: '\\mho', description: 'mho', unicode: '℧' },
  { latex: '\\Finv', description: 'Finv', unicode: 'Ⅎ' },
  { latex: '\\Bbbk', description: 'blackboard k', unicode: '𝕜' },
  { latex: '\\Game', description: 'Game', unicode: '⅁' },

  // ===== Category 4: Font commands (17, ALL with snippets) =====
  { latex: '\\mathbf{}', description: 'bold', snippet: '\\mathbf{$1}' },
  { latex: '\\mathbb{}', description: 'blackboard bold', snippet: '\\mathbb{$1}' },
  { latex: '\\mathcal{}', description: 'calligraphic', snippet: '\\mathcal{$1}' },
  { latex: '\\mathfrak{}', description: 'fraktur', snippet: '\\mathfrak{$1}' },
  { latex: '\\mathscr{}', description: 'script', snippet: '\\mathscr{$1}' },
  { latex: '\\mathsf{}', description: 'sans serif', snippet: '\\mathsf{$1}' },
  { latex: '\\mathtt{}', description: 'monospace', snippet: '\\mathtt{$1}' },
  { latex: '\\mathit{}', description: 'italic', snippet: '\\mathit{$1}' },
  { latex: '\\mathrm{}', description: 'roman', snippet: '\\mathrm{$1}' },
  { latex: '\\bm{}', description: 'bold math', snippet: '\\bm{$1}' },
  { latex: '\\boldsymbol{}', description: 'bold symbol', snippet: '\\boldsymbol{$1}' },
  { latex: '\\textrm{}', description: 'roman text', snippet: '\\textrm{$1}' },
  { latex: '\\text{}', description: 'text mode', snippet: '\\text{$1}' },
  { latex: '\\textsf{}', description: 'sans serif text', snippet: '\\textsf{$1}' },
  { latex: '\\texttt{}', description: 'typewriter text', snippet: '\\texttt{$1}' },
  { latex: '\\textbf{}', description: 'bold text', snippet: '\\textbf{$1}' },
  { latex: '\\textit{}', description: 'italic text', snippet: '\\textit{$1}' },

  // ===== Category 5: Large operators (19) =====
  { latex: '\\sum', description: 'sum', unicode: '∑' },
  { latex: '\\prod', description: 'product', unicode: '∏' },
  { latex: '\\coprod', description: 'coproduct', unicode: '∐' },
  { latex: '\\int', description: 'integral', unicode: '∫' },
  { latex: '\\iint', description: 'double integral', unicode: '∬' },
  { latex: '\\iiint', description: 'triple integral', unicode: '∭' },
  { latex: '\\oint', description: 'contour integral', unicode: '∮' },
  { latex: '\\oiint', description: 'surface integral', unicode: '∯' },
  { latex: '\\oiiint', description: 'volume integral', unicode: '∰' },
  { latex: '\\bigcap', description: 'big intersection', unicode: '⋂' },
  { latex: '\\bigcup', description: 'big union', unicode: '⋃' },
  { latex: '\\bigvee', description: 'big or', unicode: '⋁' },
  { latex: '\\bigwedge', description: 'big and', unicode: '⋀' },
  { latex: '\\bigodot', description: 'big dot', unicode: '⨀' },
  { latex: '\\bigoplus', description: 'big plus', unicode: '⨁' },
  { latex: '\\bigotimes', description: 'big times', unicode: '⨂' },
  { latex: '\\biguplus', description: 'big union plus', unicode: '⨄' },
  { latex: '\\bigsqcup', description: 'big square cup', unicode: '⨆' },
  { latex: '\\smallint', description: 'small integral', unicode: '∫' },

  // ===== Category 6: Binary operators (54) =====
  { latex: '\\times', description: 'times', unicode: '×' },
  { latex: '\\cdot', description: 'dot product', unicode: '·' },
  { latex: '\\div', description: 'divide', unicode: '÷' },
  { latex: '\\pm', description: 'plus-minus', unicode: '±' },
  { latex: '\\mp', description: 'minus-plus', unicode: '∓' },
  { latex: '\\oplus', description: 'oplus', unicode: '⊕' },
  { latex: '\\otimes', description: 'otimes', unicode: '⊗' },
  { latex: '\\circ', description: 'compose', unicode: '∘' },
  { latex: '\\cup', description: 'union', unicode: '∪' },
  { latex: '\\cap', description: 'intersection', unicode: '∩' },
  { latex: '\\wedge', description: 'wedge / and', unicode: '∧' },
  { latex: '\\vee', description: 'vee / or', unicode: '∨' },
  { latex: '\\bullet', description: 'bullet', unicode: '∙' },
  { latex: '\\star', description: 'star', unicode: '⋆' },
  { latex: '\\diamond', description: 'diamond', unicode: '⋄' },
  { latex: '\\ast', description: 'asterisk', unicode: '∗' },
  { latex: '\\odot', description: 'odot', unicode: '⊙' },
  { latex: '\\ominus', description: 'ominus', unicode: '⊖' },
  { latex: '\\oslash', description: 'oslash', unicode: '⊘' },
  { latex: '\\uplus', description: 'union plus', unicode: '⊎' },
  { latex: '\\sqcap', description: 'square cap', unicode: '⊓' },
  { latex: '\\sqcup', description: 'square cup', unicode: '⊔' },
  { latex: '\\setminus', description: 'set minus', unicode: '∖' },
  { latex: '\\wr', description: 'wreath product', unicode: '≀' },
  { latex: '\\amalg', description: 'amalg', unicode: '⨿' },
  { latex: '\\bigcirc', description: 'big circle', unicode: '○' },
  { latex: '\\bigtriangleup', description: 'big triangle up', unicode: '△' },
  { latex: '\\bigtriangledown', description: 'big triangle down', unicode: '▽' },
  { latex: '\\triangleleft', description: 'triangle left', unicode: '◃' },
  { latex: '\\triangleright', description: 'triangle right', unicode: '▹' },
  { latex: '\\lhd', description: 'lhd', unicode: '⊲' },
  { latex: '\\rhd', description: 'rhd', unicode: '⊳' },
  { latex: '\\unlhd', description: 'unlhd', unicode: '⊴' },
  { latex: '\\unrhd', description: 'unrhd', unicode: '⊵' },
  { latex: '\\dagger', description: 'dagger', unicode: '†' },
  { latex: '\\ddagger', description: 'ddagger', unicode: '‡' },
  { latex: '\\barwedge', description: 'bar wedge', unicode: '⊼' },
  { latex: '\\veebar', description: 'vee bar', unicode: '⊻' },
  { latex: '\\doublebarwedge', description: 'double bar wedge', unicode: '⩞' },
  { latex: '\\boxplus', description: 'box plus', unicode: '⊞' },
  { latex: '\\boxminus', description: 'box minus', unicode: '⊟' },
  { latex: '\\boxtimes', description: 'box times', unicode: '⊠' },
  { latex: '\\boxdot', description: 'box dot', unicode: '⊡' },
  { latex: '\\curlyvee', description: 'curly vee', unicode: '⋎' },
  { latex: '\\curlywedge', description: 'curly wedge', unicode: '⋏' },
  { latex: '\\ltimes', description: 'left times', unicode: '⋉' },
  { latex: '\\rtimes', description: 'right times', unicode: '⋊' },
  { latex: '\\leftthreetimes', description: 'left three times', unicode: '⋋' },
  { latex: '\\rightthreetimes', description: 'right three times', unicode: '⋌' },
  { latex: '\\intercal', description: 'intercal', unicode: '⊺' },
  { latex: '\\divideontimes', description: 'divide on times', unicode: '⋇' },
  { latex: '\\dotplus', description: 'dot plus', unicode: '∔' },
  { latex: '\\centerdot', description: 'center dot', unicode: '·' },
  { latex: '\\And', description: 'And', unicode: '&' },

  // ===== Category 7: Relations (85) =====
  { latex: '\\leq', description: 'less or equal', unicode: '≤' },
  { latex: '\\geq', description: 'greater or equal', unicode: '≥' },
  { latex: '\\neq', description: 'not equal', unicode: '≠' },
  { latex: '\\approx', description: 'approx', unicode: '≈' },
  { latex: '\\sim', description: 'similar', unicode: '∼' },
  { latex: '\\simeq', description: 'simeq', unicode: '≃' },
  { latex: '\\equiv', description: 'equivalent', unicode: '≡' },
  { latex: '\\propto', description: 'proportional', unicode: '∝' },
  { latex: '\\in', description: 'element of', unicode: '∈' },
  { latex: '\\notin', description: 'not in', unicode: '∉' },
  { latex: '\\subset', description: 'subset', unicode: '⊂' },
  { latex: '\\subseteq', description: 'subset or equal', unicode: '⊆' },
  { latex: '\\supset', description: 'superset', unicode: '⊃' },
  { latex: '\\supseteq', description: 'superset or equal', unicode: '⊇' },
  { latex: '\\prec', description: 'precedes', unicode: '≺' },
  { latex: '\\succ', description: 'succeeds', unicode: '≻' },
  { latex: '\\preceq', description: 'precedes or equal', unicode: '≼' },
  { latex: '\\succeq', description: 'succeeds or equal', unicode: '≽' },
  { latex: '\\ll', description: 'much less', unicode: '≪' },
  { latex: '\\gg', description: 'much greater', unicode: '≫' },
  { latex: '\\lll', description: 'triple less', unicode: '⋘' },
  { latex: '\\ggg', description: 'triple greater', unicode: '⋙' },
  { latex: '\\subsetneq', description: 'subset not equal', unicode: '⊊' },
  { latex: '\\supsetneq', description: 'superset not equal', unicode: '⊋' },
  { latex: '\\ni', description: 'contains', unicode: '∋' },
  { latex: '\\notni', description: 'not contains', unicode: '∌' },
  { latex: '\\mid', description: 'mid', unicode: '∣' },
  { latex: '\\nmid', description: 'not mid', unicode: '∤' },
  { latex: '\\parallel', description: 'parallel', unicode: '∥' },
  { latex: '\\nparallel', description: 'not parallel', unicode: '∦' },
  { latex: '\\perp', description: 'perpendicular', unicode: '⊥' },
  { latex: '\\models', description: 'models', unicode: '⊧' },
  { latex: '\\vdash', description: 'vdash', unicode: '⊢' },
  { latex: '\\dashv', description: 'dashv', unicode: '⊣' },
  { latex: '\\Vdash', description: 'Vdash', unicode: '⊩' },
  { latex: '\\vDash', description: 'vDash', unicode: '⊨' },
  { latex: '\\nvdash', description: 'not vdash', unicode: '⊬' },
  { latex: '\\nvDash', description: 'not vDash', unicode: '⊭' },
  { latex: '\\smile', description: 'smile', unicode: '⌣' },
  { latex: '\\frown', description: 'frown', unicode: '⌢' },
  { latex: '\\asymp', description: 'asymptotic', unicode: '≍' },
  { latex: '\\bowtie', description: 'bowtie', unicode: '⋈' },
  { latex: '\\doteq', description: 'doteq', unicode: '≐' },
  { latex: '\\doteqdot', description: 'doteqdot', unicode: '≑' },
  { latex: '\\fallingdotseq', description: 'falling dotseq', unicode: '≒' },
  { latex: '\\risingdotseq', description: 'rising dotseq', unicode: '≓' },
  { latex: '\\eqcirc', description: 'eqcirc', unicode: '≖' },
  { latex: '\\circeq', description: 'circeq', unicode: '≗' },
  { latex: '\\triangleq', description: 'triangle equal', unicode: '≜' },
  { latex: '\\bumpeq', description: 'bumpeq', unicode: '≏' },
  { latex: '\\Bumpeq', description: 'Bumpeq', unicode: '≎' },
  { latex: '\\leqq', description: 'leqq', unicode: '≦' },
  { latex: '\\geqq', description: 'geqq', unicode: '≧' },
  { latex: '\\lneqq', description: 'less not equal', unicode: '≨' },
  { latex: '\\gneqq', description: 'greater not equal', unicode: '≩' },
  { latex: '\\lneq', description: 'lneq', unicode: '⪇' },
  { latex: '\\gneq', description: 'gneq', unicode: '⪈' },
  { latex: '\\lnsim', description: 'lnsim', unicode: '⋦' },
  { latex: '\\gnsim', description: 'gnsim', unicode: '⋧' },
  { latex: '\\lesssim', description: 'less sim', unicode: '≲' },
  { latex: '\\gtrsim', description: 'greater sim', unicode: '≳' },
  { latex: '\\lessapprox', description: 'less approx', unicode: '⪅' },
  { latex: '\\gtrapprox', description: 'greater approx', unicode: '⪆' },
  { latex: '\\lessgtr', description: 'less greater', unicode: '≶' },
  { latex: '\\gtrless', description: 'greater less', unicode: '≷' },
  { latex: '\\lesseqgtr', description: 'less eq greater', unicode: '⋚' },
  { latex: '\\gtreqless', description: 'greater eq less', unicode: '⋛' },
  { latex: '\\lesseqqgtr', description: 'less eqq greater', unicode: '⪋' },
  { latex: '\\gtreqqless', description: 'greater eqq less', unicode: '⪌' },
  { latex: '\\precapprox', description: 'prec approx', unicode: '⪷' },
  { latex: '\\succapprox', description: 'succ approx', unicode: '⪸' },
  { latex: '\\precnapprox', description: 'prec napprox', unicode: '⪹' },
  { latex: '\\succnapprox', description: 'succ napprox', unicode: '⪺' },
  { latex: '\\precsim', description: 'prec sim', unicode: '≾' },
  { latex: '\\succsim', description: 'succ sim', unicode: '≿' },
  { latex: '\\precneqq', description: 'prec neqq', unicode: '⪵' },
  { latex: '\\succneqq', description: 'succ neqq', unicode: '⪶' },
  { latex: '\\curlyeqprec', description: 'curly eq prec', unicode: '⋞' },
  { latex: '\\curlyeqsucc', description: 'curly eq succ', unicode: '⋟' },
  { latex: '\\trianglelefteq', description: 'triangle left eq', unicode: '⊴' },
  { latex: '\\trianglerighteq', description: 'triangle right eq', unicode: '⊵' },
  { latex: '\\between', description: 'between', unicode: '≬' },
  { latex: '\\pitchfork', description: 'pitchfork', unicode: '⋔' },
  { latex: '\\shortmid', description: 'short mid', unicode: '∣' },
  { latex: '\\shortparallel', description: 'short parallel', unicode: '∥' },
  { latex: '\\smallfrown', description: 'small frown', unicode: '⌢' },
  { latex: '\\smallsmile', description: 'small smile', unicode: '⌣' },
  { latex: '\\backsim', description: 'back sim', unicode: '∽' },
  { latex: '\\backsimeq', description: 'back simeq', unicode: '⋍' },
  { latex: '\\eqsim', description: 'eq sim', unicode: '≂' },
  { latex: '\\approxeq', description: 'approx eq', unicode: '≊' },

  // ===== Category 8: Arrows (55) =====
  { latex: '\\to', description: 'arrow right', unicode: '→' },
  { latex: '\\rightarrow', description: 'right arrow', unicode: '→' },
  { latex: '\\longrightarrow', description: 'long right arrow', unicode: '⟶' },
  { latex: '\\leftarrow', description: 'arrow left', unicode: '←' },
  { latex: '\\longleftarrow', description: 'long left arrow', unicode: '⟵' },
  { latex: '\\leftrightarrow', description: 'arrow both', unicode: '↔' },
  { latex: '\\longleftrightarrow', description: 'long left right arrow', unicode: '⟷' },
  { latex: '\\Rightarrow', description: 'implies', unicode: '⇒' },
  { latex: '\\Longrightarrow', description: 'long implies', unicode: '⟹' },
  { latex: '\\Leftarrow', description: 'implied by', unicode: '⇐' },
  { latex: '\\Longleftarrow', description: 'long implied by', unicode: '⟸' },
  { latex: '\\Leftrightarrow', description: 'iff', unicode: '⇔' },
  { latex: '\\Longleftrightarrow', description: 'long iff', unicode: '⟺' },
  { latex: '\\mapsto', description: 'maps to', unicode: '↦' },
  { latex: '\\longmapsto', description: 'long maps to', unicode: '⟼' },
  { latex: '\\hookrightarrow', description: 'hook right arrow', unicode: '↪' },
  { latex: '\\hookleftarrow', description: 'hook left arrow', unicode: '↩' },
  { latex: '\\rightharpoonup', description: 'right harpoon up', unicode: '⇀' },
  { latex: '\\leftharpoonup', description: 'left harpoon up', unicode: '↼' },
  { latex: '\\rightharpoondown', description: 'right harpoon down', unicode: '⇁' },
  { latex: '\\leftharpoondown', description: 'left harpoon down', unicode: '↽' },
  { latex: '\\rightleftharpoons', description: 'right left harpoons', unicode: '⇌' },
  { latex: '\\leftrightharpoons', description: 'left right harpoons', unicode: '⇋' },
  { latex: '\\nearrow', description: 'north east arrow', unicode: '↗' },
  { latex: '\\searrow', description: 'south east arrow', unicode: '↘' },
  { latex: '\\swarrow', description: 'south west arrow', unicode: '↙' },
  { latex: '\\nwarrow', description: 'north west arrow', unicode: '↖' },
  { latex: '\\uparrow', description: 'up arrow', unicode: '↑' },
  { latex: '\\downarrow', description: 'down arrow', unicode: '↓' },
  { latex: '\\updownarrow', description: 'up down arrow', unicode: '↕' },
  { latex: '\\Uparrow', description: 'double up arrow', unicode: '⇑' },
  { latex: '\\Downarrow', description: 'double down arrow', unicode: '⇓' },
  { latex: '\\Updownarrow', description: 'double up down arrow', unicode: '⇕' },
  { latex: '\\twoheadrightarrow', description: 'twohead right', unicode: '↠' },
  { latex: '\\twoheadleftarrow', description: 'twohead left', unicode: '↞' },
  { latex: '\\rightarrowtail', description: 'right arrow tail', unicode: '↣' },
  { latex: '\\leftarrowtail', description: 'left arrow tail', unicode: '↢' },
  { latex: '\\looparrowleft', description: 'loop arrow left', unicode: '↫' },
  { latex: '\\looparrowright', description: 'loop arrow right', unicode: '↬' },
  { latex: '\\circlearrowleft', description: 'circle arrow left', unicode: '↺' },
  { latex: '\\circlearrowright', description: 'circle arrow right', unicode: '↻' },
  { latex: '\\curvearrowleft', description: 'curve arrow left', unicode: '↶' },
  { latex: '\\curvearrowright', description: 'curve arrow right', unicode: '↷' },
  { latex: '\\dashrightarrow', description: 'dash right arrow', unicode: '⇢' },
  { latex: '\\dashleftarrow', description: 'dash left arrow', unicode: '⇠' },
  { latex: '\\Lsh', description: 'Lsh', unicode: '↰' },
  { latex: '\\Rsh', description: 'Rsh', unicode: '↱' },
  { latex: '\\multimap', description: 'multimap', unicode: '⊸' },
  { latex: '\\rightsquigarrow', description: 'right squiggle', unicode: '⇝' },
  { latex: '\\leftrightsquigarrow', description: 'left right squiggle', unicode: '↭' },
  { latex: '\\nleftarrow', description: 'not left arrow', unicode: '↚' },
  { latex: '\\nrightarrow', description: 'not right arrow', unicode: '↛' },
  { latex: '\\nLeftarrow', description: 'not double left arrow', unicode: '⇍' },
  { latex: '\\nRightarrow', description: 'not double right arrow', unicode: '⇏' },
  { latex: '\\nleftrightarrow', description: 'not left right arrow', unicode: '↮' },
  { latex: '\\nLeftrightarrow', description: 'not double left right arrow', unicode: '⇎' },

  // ===== Category 9: Logic/set theory (23) =====
  { latex: '\\forall', description: 'for all', unicode: '∀' },
  { latex: '\\exists', description: 'exists', unicode: '∃' },
  { latex: '\\nexists', description: 'does not exist', unicode: '∄' },
  { latex: '\\neg', description: 'negation', unicode: '¬' },
  { latex: '\\land', description: 'logical and', unicode: '∧' },
  { latex: '\\lor', description: 'logical or', unicode: '∨' },
  { latex: '\\top', description: 'top', unicode: '⊤' },
  { latex: '\\bot', description: 'bottom', unicode: '⊥' },
  { latex: '\\therefore', description: 'therefore', unicode: '∴' },
  { latex: '\\because', description: 'because', unicode: '∵' },
  { latex: '\\varnothing', description: 'empty set (var)', unicode: '∅' },
  { latex: '\\complement', description: 'complement', unicode: '∁' },

  // ===== Category 10: Calculus/analysis (16) =====
  { latex: '\\partial', description: 'partial derivative', unicode: '∂' },
  { latex: '\\nabla', description: 'nabla / gradient', unicode: '∇' },
  { latex: '\\infty', description: 'infinity', unicode: '∞' },
  { latex: '\\lim', description: 'limit' },
  { latex: '\\liminf', description: 'limit inferior' },
  { latex: '\\limsup', description: 'limit superior' },
  { latex: '\\sup', description: 'supremum' },
  { latex: '\\inf', description: 'infimum' },
  { latex: '\\max', description: 'maximum' },
  { latex: '\\min', description: 'minimum' },

  // ===== Category 11: Trig/hyperbolic (16) =====
  { latex: '\\sin', description: 'sine' },
  { latex: '\\cos', description: 'cosine' },
  { latex: '\\tan', description: 'tangent' },
  { latex: '\\sec', description: 'secant' },
  { latex: '\\csc', description: 'cosecant' },
  { latex: '\\cot', description: 'cotangent' },
  { latex: '\\sinh', description: 'hyperbolic sine' },
  { latex: '\\cosh', description: 'hyperbolic cosine' },
  { latex: '\\tanh', description: 'hyperbolic tangent' },
  { latex: '\\coth', description: 'hyperbolic cotangent' },
  { latex: '\\arcsin', description: 'arc sine' },
  { latex: '\\arccos', description: 'arc cosine' },
  { latex: '\\arctan', description: 'arc tangent' },
  { latex: '\\arcsec', description: 'arc secant' },
  { latex: '\\arccsc', description: 'arc cosecant' },
  { latex: '\\arccot', description: 'arc cotangent' },

  // ===== Category 12: Other operators (12) =====
  { latex: '\\arg', description: 'argument' },
  { latex: '\\deg', description: 'degree' },
  { latex: '\\det', description: 'determinant' },
  { latex: '\\dim', description: 'dimension' },
  { latex: '\\exp', description: 'exponential' },
  { latex: '\\gcd', description: 'greatest common divisor' },
  { latex: '\\hom', description: 'homomorphism' },
  { latex: '\\ker', description: 'kernel' },
  { latex: '\\lg', description: 'log base 10' },
  { latex: '\\ln', description: 'natural log' },
  { latex: '\\log', description: 'logarithm' },
  { latex: '\\Pr', description: 'probability' },

  // ===== Category 13: Delimiters (18) =====
  { latex: '\\langle', description: 'left angle bracket', unicode: '⟨' },
  { latex: '\\rangle', description: 'right angle bracket', unicode: '⟩' },
  { latex: '\\lceil', description: 'left ceiling', unicode: '⌈' },
  { latex: '\\rceil', description: 'right ceiling', unicode: '⌉' },
  { latex: '\\lfloor', description: 'left floor', unicode: '⌊' },
  { latex: '\\rfloor', description: 'right floor', unicode: '⌋' },
  { latex: '\\lbrace', description: 'left brace', unicode: '{' },
  { latex: '\\rbrace', description: 'right brace', unicode: '}' },
  { latex: '\\lvert', description: 'left vertical bar', unicode: '|' },
  { latex: '\\rvert', description: 'right vertical bar', unicode: '|' },
  { latex: '\\lVert', description: 'left double bar', unicode: '‖' },
  { latex: '\\rVert', description: 'right double bar', unicode: '‖' },
  { latex: '\\llbracket', description: 'left double bracket', unicode: '⟦' },
  { latex: '\\rrbracket', description: 'right double bracket', unicode: '⟧' },
  { latex: '\\ulcorner', description: 'upper left corner', unicode: '┌' },
  { latex: '\\urcorner', description: 'upper right corner', unicode: '┐' },
  { latex: '\\llcorner', description: 'lower left corner', unicode: '└' },
  { latex: '\\lrcorner', description: 'lower right corner', unicode: '┘' },

  // ===== Category 14: Decorations/accents (19, most with snippets) =====
  { latex: '\\hat{}', description: 'hat accent', snippet: '\\hat{$1}' },
  { latex: '\\bar{}', description: 'bar accent', snippet: '\\bar{$1}' },
  { latex: '\\vec{}', description: 'vector arrow', snippet: '\\vec{$1}' },
  { latex: '\\dot{}', description: 'dot accent', snippet: '\\dot{$1}' },
  { latex: '\\ddot{}', description: 'double dot', snippet: '\\ddot{$1}' },
  { latex: '\\widehat{}', description: 'wide hat', snippet: '\\widehat{$1}' },
  { latex: '\\widetilde{}', description: 'wide tilde', snippet: '\\widetilde{$1}' },
  { latex: '\\overline{}', description: 'overline', snippet: '\\overline{$1}' },
  { latex: '\\underline{}', description: 'underline', snippet: '\\underline{$1}' },
  { latex: '\\overbrace{}{}', description: 'overbrace', snippet: '\\overbrace{$1}{$2}' },
  { latex: '\\underbrace{}{}', description: 'underbrace', snippet: '\\underbrace{$1}{$2}' },
  { latex: '\\acute{}', description: 'acute accent', snippet: '\\acute{$1}' },
  { latex: '\\grave{}', description: 'grave accent', snippet: '\\grave{$1}' },
  { latex: '\\breve{}', description: 'breve accent', snippet: '\\breve{$1}' },
  { latex: '\\check{}', description: 'check accent', snippet: '\\check{$1}' },
  { latex: '\\tilde{}', description: 'tilde accent', snippet: '\\tilde{$1}' },
  { latex: '\\mathring{}', description: 'math ring', snippet: '\\mathring{$1}' },
  { latex: '\\dddot{}', description: 'triple dot', snippet: '\\dddot{$1}' },
  { latex: '\\ddddot{}', description: 'quadruple dot', snippet: '\\ddddot{$1}' },

  // ===== Category 15: Fractions/binomials (6, ALL with snippets) =====
  { latex: '\\frac{}{}', description: 'fraction', snippet: '\\frac{$1}{$2}' },
  { latex: '\\dfrac{}{}', description: 'display fraction', snippet: '\\dfrac{$1}{$2}' },
  { latex: '\\tfrac{}{}', description: 'text fraction', snippet: '\\tfrac{$1}{$2}' },
  { latex: '\\binom{}{}', description: 'binomial', snippet: '\\binom{$1}{$2}' },
  { latex: '\\dbinom{}{}', description: 'display binomial', snippet: '\\dbinom{$1}{$2}' },
  { latex: '\\tbinom{}{}', description: 'text binomial', snippet: '\\tbinom{$1}{$2}' },

  // ===== Category 16: Stacking/extensible arrows (10, most with snippets) =====
  { latex: '\\overset{}{}', description: 'overset', snippet: '\\overset{$1}{$2}' },
  { latex: '\\underset{}{}', description: 'underset', snippet: '\\underset{$1}{$2}' },
  { latex: '\\stackrel{}{}', description: 'stackrel', snippet: '\\stackrel{$1}{$2}' },
  { latex: '\\xrightarrow{}', description: 'extensible right arrow', snippet: '\\xrightarrow{$1}' },
  { latex: '\\xleftarrow{}', description: 'extensible left arrow', snippet: '\\xleftarrow{$1}' },
  { latex: '\\xleftrightarrow{}', description: 'extensible left right arrow', snippet: '\\xleftrightarrow{$1}' },
  { latex: '\\xmapsto{}', description: 'extensible maps to', snippet: '\\xmapsto{$1}' },
  { latex: '\\xhookleftarrow{}', description: 'extensible hook left arrow', snippet: '\\xhookleftarrow{$1}' },
  { latex: '\\xhookrightarrow{}', description: 'extensible hook right arrow', snippet: '\\xhookrightarrow{$1}' },
  { latex: '\\xlongequal{}', description: 'extensible long equal', snippet: '\\xlongequal{$1}' },

  // ===== Category 17: Misc symbols (60+) =====
  { latex: '\\eth', description: 'eth', unicode: 'ð' },
  { latex: '\\S', description: 'section', unicode: '§' },
  { latex: '\\P', description: 'pilcrow', unicode: '¶' },
  { latex: '\\dag', description: 'dagger', unicode: '†' },
  { latex: '\\ddag', description: 'double dagger', unicode: '‡' },
  { latex: '\\copyright', description: 'copyright', unicode: '©' },
  { latex: '\\pounds', description: 'pounds', unicode: '£' },
  { latex: '\\angle', description: 'angle', unicode: '∠' },
  { latex: '\\measuredangle', description: 'measured angle', unicode: '∡' },
  { latex: '\\sphericalangle', description: 'spherical angle', unicode: '∢' },
  { latex: '\\surd', description: 'surd', unicode: '√' },
  { latex: '\\dots', description: 'dots', unicode: '…' },
  { latex: '\\iddots', description: 'inverse dots', unicode: '⋰' },
  { latex: '\\square', description: 'square', unicode: '□' },
  { latex: '\\Box', description: 'Box', unicode: '□' },
  { latex: '\\blacksquare', description: 'black square', unicode: '■' },
  { latex: '\\triangle', description: 'triangle', unicode: '△' },
  { latex: '\\triangledown', description: 'triangle down', unicode: '▽' },
  { latex: '\\lozenge', description: 'lozenge', unicode: '◊' },
  { latex: '\\blacklozenge', description: 'black lozenge', unicode: '⧫' },
  { latex: '\\Diamond', description: 'Diamond', unicode: '◇' },
  { latex: '\\blacktriangle', description: 'black triangle', unicode: '▲' },
  { latex: '\\blacktriangledown', description: 'black triangle down', unicode: '▼' },
  { latex: '\\blacktriangleleft', description: 'black triangle left', unicode: '◀' },
  { latex: '\\blacktriangleright', description: 'black triangle right', unicode: '▶' },
  { latex: '\\bigstar', description: 'big star', unicode: '★' },
  { latex: '\\clubsuit', description: 'club suit', unicode: '♣' },
  { latex: '\\diamondsuit', description: 'diamond suit', unicode: '♢' },
  { latex: '\\heartsuit', description: 'heart suit', unicode: '♡' },
  { latex: '\\spadesuit', description: 'spade suit', unicode: '♠' },
  { latex: '\\sharp', description: 'sharp', unicode: '♯' },
  { latex: '\\flat', description: 'flat', unicode: '♭' },
  { latex: '\\natural', description: 'natural', unicode: '♮' },
  { latex: '\\prime', description: 'prime', unicode: '′' },
  { latex: '\\backprime', description: 'back prime', unicode: '‵' },
  { latex: '\\backslash', description: 'backslash', unicode: '\\' },
  { latex: '\\diagup', description: 'diagonal up', unicode: '╱' },
  { latex: '\\diagdown', description: 'diagonal down', unicode: '╲' },

  // ===== Category 18: Math font styles (4, no snippet) =====
  { latex: '\\displaystyle', description: 'display style' },
  { latex: '\\textstyle', description: 'text style' },
  { latex: '\\scriptstyle', description: 'script style' },
  { latex: '\\scriptscriptstyle', description: 'scriptscript style' },

  // ===== Category 19: Spacing (13, no snippet) =====
  { latex: '\\,', description: 'thin space' },
  { latex: '\\;', description: 'thick space' },
  { latex: '\\:', description: 'medium space' },
  { latex: '\\!', description: 'negative thin space' },
  { latex: '\\quad', description: 'quad space' },
  { latex: '\\qquad', description: 'double quad space' },
  { latex: '\\enspace', description: 'en space' },
  { latex: '\\thinspace', description: 'thin space (alias)' },
  { latex: '\\thickspace', description: 'thick space (alias)' },
  { latex: '\\medspace', description: 'medium space (alias)' },
  { latex: '\\negthinspace', description: 'negative thin space (alias)' },
  { latex: '\\negmedspace', description: 'negative medium space' },
  { latex: '\\negthickspace', description: 'negative thick space' },

  // ===== Category 20: Environment starters (15, no snippet) =====
  { latex: '{pmatrix}', description: 'parenthesis matrix' },
  { latex: '{bmatrix}', description: 'bracket matrix' },
  { latex: '{Bmatrix}', description: 'brace matrix' },
  { latex: '{vmatrix}', description: 'vertical bar matrix' },
  { latex: '{Vmatrix}', description: 'double bar matrix' },
  { latex: '{matrix}', description: 'plain matrix' },
  { latex: '{cases}', description: 'cases environment' },
  { latex: '{rcases}', description: 'reverse cases' },
  { latex: '{dcases}', description: 'display cases' },
  { latex: '{aligned}', description: 'aligned environment' },
  { latex: '{gathered}', description: 'gathered environment' },
  { latex: '{array}', description: 'array environment' },
  { latex: '{split}', description: 'split environment' },
  { latex: '{smallmatrix}', description: 'small matrix' },
  { latex: '{CD}', description: 'CD environment' },

  // ===== Category 21: Root/box (3, all with snippets) =====
  { latex: '\\sqrt{}', description: 'square root', snippet: '\\sqrt{$1}' },
  { latex: '\\sqrt[]{}', description: 'nth root', snippet: '\\sqrt[$1]{$2}' },
  { latex: '\\boxed{}', description: 'boxed expression', snippet: '\\boxed{$1}' },

  // ===== Category 22: Color (4, all with snippets) =====
  { latex: '\\color{}{}', description: 'set color', snippet: '\\color{$1}{$2}' },
  { latex: '\\textcolor{}{}', description: 'text color', snippet: '\\textcolor{$1}{$2}' },
  { latex: '\\colorbox{}{}', description: 'colored box', snippet: '\\colorbox{$1}{$2}' },
  { latex: '\\fcolorbox{}{}{}', description: 'framed color box', snippet: '\\fcolorbox{$1}{$2}{$3}' },

  // ===== Category 23: Annotation/cancel (5, most with snippets) =====
  { latex: '\\cancel{}', description: 'cancel', snippet: '\\cancel{$1}' },
  { latex: '\\bcancel{}', description: 'cancel (back)', snippet: '\\bcancel{$1}' },
  { latex: '\\xcancel{}', description: 'cancel (X)', snippet: '\\xcancel{$1}' },
  { latex: '\\sout{}', description: 'strike out', snippet: '\\sout{$1}' },
  { latex: '\\not', description: 'not' },
];

// Populate the lookup map AFTER the array is fully defined
for (const sym of MATH_SYMBOLS) {
  MATH_SYMBOLS_BY_LATEX.set(sym.latex, sym);
}
