export interface MathSymbol {
  latex: string;
  description: string;
  unicode?: string;
}

export const MATH_SYMBOLS: MathSymbol[] = [
  // Greek lowercase
  { latex: '\\alpha', description: 'alpha', unicode: 'α' },
  { latex: '\\beta', description: 'beta', unicode: 'β' },
  { latex: '\\gamma', description: 'gamma', unicode: 'γ' },
  { latex: '\\delta', description: 'delta', unicode: 'δ' },
  { latex: '\\epsilon', description: 'epsilon', unicode: 'ε' },
  { latex: '\\varepsilon', description: 'epsilon (var)', unicode: 'ε' },
  { latex: '\\zeta', description: 'zeta', unicode: 'ζ' },
  { latex: '\\eta', description: 'eta', unicode: 'η' },
  { latex: '\\theta', description: 'theta', unicode: 'θ' },
  { latex: '\\vartheta', description: 'theta (var)', unicode: 'ϑ' },
  { latex: '\\iota', description: 'iota', unicode: 'ι' },
  { latex: '\\kappa', description: 'kappa', unicode: 'κ' },
  { latex: '\\lambda', description: 'lambda', unicode: 'λ' },
  { latex: '\\mu', description: 'mu', unicode: 'μ' },
  { latex: '\\nu', description: 'nu', unicode: 'ν' },
  { latex: '\\xi', description: 'xi', unicode: 'ξ' },
  { latex: '\\pi', description: 'pi', unicode: 'π' },
  { latex: '\\varpi', description: 'pi (var)', unicode: 'ϖ' },
  { latex: '\\rho', description: 'rho', unicode: 'ρ' },
  { latex: '\\sigma', description: 'sigma', unicode: 'σ' },
  { latex: '\\varsigma', description: 'sigma (var)', unicode: 'ς' },
  { latex: '\\tau', description: 'tau', unicode: 'τ' },
  { latex: '\\upsilon', description: 'upsilon', unicode: 'υ' },
  { latex: '\\phi', description: 'phi', unicode: 'φ' },
  { latex: '\\varphi', description: 'phi (var)', unicode: 'φ' },
  { latex: '\\chi', description: 'chi', unicode: 'χ' },
  { latex: '\\psi', description: 'psi', unicode: 'ψ' },
  { latex: '\\omega', description: 'omega', unicode: 'ω' },
  // Greek uppercase
  { latex: '\\Gamma', description: 'Gamma', unicode: 'Γ' },
  { latex: '\\Delta', description: 'Delta', unicode: 'Δ' },
  { latex: '\\Theta', description: 'Theta', unicode: 'Θ' },
  { latex: '\\Lambda', description: 'Lambda', unicode: 'Λ' },
  { latex: '\\Xi', description: 'Xi', unicode: 'Ξ' },
  { latex: '\\Pi', description: 'Pi', unicode: 'Π' },
  { latex: '\\Sigma', description: 'Sigma', unicode: 'Σ' },
  { latex: '\\Upsilon', description: 'Upsilon', unicode: 'Υ' },
  { latex: '\\Phi', description: 'Phi', unicode: 'Φ' },
  { latex: '\\Psi', description: 'Psi', unicode: 'Ψ' },
  { latex: '\\Omega', description: 'Omega', unicode: 'Ω' },
  // Large operators
  { latex: '\\sum', description: 'sum', unicode: '∑' },
  { latex: '\\prod', description: 'product', unicode: '∏' },
  { latex: '\\int', description: 'integral', unicode: '∫' },
  { latex: '\\iint', description: 'double integral', unicode: '∬' },
  { latex: '\\iiint', description: 'triple integral', unicode: '∭' },
  { latex: '\\oint', description: 'contour integral', unicode: '∮' },
  { latex: '\\bigcup', description: 'big union', unicode: '⋃' },
  { latex: '\\bigcap', description: 'big intersection', unicode: '⋂' },
  // Binary operators
  { latex: '\\times', description: 'times', unicode: '×' },
  { latex: '\\cdot', description: 'dot product', unicode: '·' },
  { latex: '\\div', description: 'divide', unicode: '÷' },
  { latex: '\\pm', description: 'plus-minus', unicode: '±' },
  { latex: '\\mp', description: 'minus-plus', unicode: '∓' },
  { latex: '\\oplus', description: 'oplus', unicode: '⊕' },
  { latex: '\\otimes', description: 'otimes', unicode: '⊗' },
  { latex: '\\circ', description: 'compose', unicode: '∘' },
  { latex: '\\wedge', description: 'wedge / and', unicode: '∧' },
  { latex: '\\vee', description: 'vee / or', unicode: '∨' },
  { latex: '\\cup', description: 'union', unicode: '∪' },
  { latex: '\\cap', description: 'intersection', unicode: '∩' },
  // Relations
  { latex: '\\leq', description: 'less or equal', unicode: '≤' },
  { latex: '\\geq', description: 'greater or equal', unicode: '≥' },
  { latex: '\\neq', description: 'not equal', unicode: '≠' },
  { latex: '\\approx', description: 'approx', unicode: '≈' },
  { latex: '\\sim', description: 'similar', unicode: '∼' },
  { latex: '\\simeq', description: 'simeq', unicode: '≃' },
  { latex: '\\equiv', description: 'equivalent', unicode: '≡' },
  { latex: '\\propto', description: 'proportional', unicode: '∝' },
  { latex: '\\in', description: 'element of', unicode: '∈' },
  { latex: '\\notin', description: 'not in', unicode: '∉' },
  { latex: '\\subset', description: 'subset', unicode: '⊂' },
  { latex: '\\subseteq', description: 'subset or equal', unicode: '⊆' },
  { latex: '\\supset', description: 'superset', unicode: '⊃' },
  { latex: '\\supseteq', description: 'superset or equal', unicode: '⊇' },
  // Arrows
  { latex: '\\to', description: 'arrow right', unicode: '→' },
  { latex: '\\leftarrow', description: 'arrow left', unicode: '←' },
  { latex: '\\leftrightarrow', description: 'arrow both', unicode: '↔' },
  { latex: '\\Rightarrow', description: 'implies', unicode: '⇒' },
  { latex: '\\Leftarrow', description: 'implied by', unicode: '⇐' },
  { latex: '\\Leftrightarrow', description: 'iff', unicode: '⇔' },
  { latex: '\\mapsto', description: 'maps to', unicode: '↦' },
  // Calculus / analysis
  { latex: '\\partial', description: 'partial derivative', unicode: '∂' },
  { latex: '\\nabla', description: 'nabla / gradient', unicode: '∇' },
  { latex: '\\infty', description: 'infinity', unicode: '∞' },
  { latex: '\\lim', description: 'limit' },
  { latex: '\\frac{}{}', description: 'fraction' },
  { latex: '\\sqrt{}', description: 'square root' },
  { latex: '\\hat{}', description: 'hat accent' },
  { latex: '\\bar{}', description: 'bar accent' },
  { latex: '\\vec{}', description: 'vector arrow' },
  { latex: '\\dot{}', description: 'dot accent' },
  { latex: '\\ddot{}', description: 'double dot' },
  // Misc
  { latex: '\\forall', description: 'for all', unicode: '∀' },
  { latex: '\\exists', description: 'exists', unicode: '∃' },
  { latex: '\\neg', description: 'negation', unicode: '¬' },
  { latex: '\\emptyset', description: 'empty set', unicode: '∅' },
  { latex: '\\mathbb{R}', description: 'real numbers', unicode: 'ℝ' },
  { latex: '\\mathbb{N}', description: 'natural numbers', unicode: 'ℕ' },
  { latex: '\\mathbb{Z}', description: 'integers', unicode: 'ℤ' },
  { latex: '\\mathbb{C}', description: 'complex numbers', unicode: 'ℂ' },
  { latex: '\\mathbb{Q}', description: 'rationals', unicode: 'ℚ' },
  { latex: '\\ldots', description: 'dots (low)', unicode: '…' },
  { latex: '\\cdots', description: 'dots (center)', unicode: '⋯' },
  { latex: '\\vdots', description: 'dots (vertical)', unicode: '⋮' },
  { latex: '\\ddots', description: 'dots (diagonal)', unicode: '⋱' },
];
